In [90]:
# generate a pandas dataframe of 3 columns and 10 rows with random numbers
# between 0 and 100
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randint(0, 100, size=(10, 3)),
                    columns=['First', 'Second', 'Third'])

print(df)

   First  Second  Third
0     37      28     21
1     40       7     82
2     72       1     16
3     59      65     28
4     65      27     26
5      6      85     48
6     11      13     67
7      9      77     44
8     17      84     46
9     63      23     56


In [91]:
# use standard scaler
df1 = df.copy()
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
print(scaler.fit(df1))
print(scaler.mean_)
print(scaler.transform(df1))

StandardScaler()
[37.9 41.  43.4]
[[-0.03677024 -0.41345957 -1.1163222 ]
 [ 0.08579723 -1.0813558   1.92366235]
 [ 1.39318357 -1.27218329 -1.36550126]
 [ 0.86205787  0.76330998 -0.76747151]
 [ 1.10719281 -0.44526415 -0.86714313]
 [-1.30330076  1.39940162  0.22924474]
 [-1.09902164 -0.89052831  1.17612517]
 [-1.18073329  1.14496496  0.02990149]
 [-0.8538867   1.36759704  0.12957311]
 [ 1.02548116 -0.57248248  0.62793123]]


In [92]:
df2 = df.copy()
for col in df.columns:
    col_mean = df2[col].mean()
    col_std = df2[col].std()
    df2[col] = df2[col].apply(lambda x: (x - col_mean) / col_std)

print (df2)

      First    Second     Third
0 -0.034883 -0.392242 -1.059036
1  0.081394 -1.025864  1.824946
2  1.321690 -1.206899 -1.295428
3  0.817820  0.724139 -0.728087
4  1.050375 -0.422415 -0.822644
5 -1.236420  1.327589  0.217481
6 -1.042623 -0.844829  1.115770
7 -1.120142  1.086209  0.028367
8 -0.810068  1.297416  0.122924
9  0.972857 -0.543105  0.595708
